/**
 * Bakes the static OG fallback poster, once, at authoring time.
 *
 * The live/frozen OG routes must never fall back to SVG: LinkedIn's crawler
 * cannot parse it and shows "No image found". They serve this PNG instead, read
 * as bytes with no dependency on the renderer service, so a renderer outage can
 * never turn into a broken preview.
 *
 * Run: bun scripts/build-og-fallback.ts
 */
import { writeFileSync, mkdirSync } from "node:fs";

import { Resvg } from "@resvg/resvg-js";

import { buildShareSvg } from "@/lib/intelligence/share-image.server";

const card = {
  id: "fallback",
  value: "CostMyAI",
  label: "Intelligence",
  detail: "Live provider pricing and margin signal.",
  tone: "brand" as const,
};

// The month stamp is swapped out afterwards: this poster is static and must
// not claim a month, or a timestamp, that it cannot vouch for.
let svg = buildShareSvg(card as never, {
  kind: "live",
  monthLabel: "",
  generatedAt: new Date().toISOString(),
});
svg = svg.replace(
  /<tspan font-size="24" font-weight="600"[^>]*>[^<]*<\/tspan>[^<]*/,
  '<tspan font-size="24" font-weight="600" fill="#11131D">CostMyAI Intelligence</tspan> · live provider pricing, updated continuously',
);

const css = await fetch(
  "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700",
).then((r) => r.text());
const urls = [...css.matchAll(/url\((https:\/\/[^)]+\.ttf)\)/g)].map((m) => m[1]);
const fontBuffers = await Promise.all(
  urls.map(async (u) => Buffer.from(await (await fetch(u)).arrayBuffer())),
);

const png = new Resvg(svg, {
  fitTo: { mode: "width", value: 1200 },
  font: { fontBuffers, defaultFontFamily: "Inter", loadSystemFonts: false },
})
  .render()
  .asPng();

mkdirSync("public/images/og", { recursive: true });
writeFileSync("public/images/og/intelligence-fallback.png", png);

// The Worker runtime has no access to public/ at request time, so the same
// bytes are also emitted as a base64 module the routes can import directly.
mkdirSync("src/lib/intelligence/generated", { recursive: true });
writeFileSync(
  "src/lib/intelligence/generated/og-fallback-png.ts",
  `/**
 * Generated by scripts/build-og-fallback.ts. Do not edit by hand.
 *
 * The static OG fallback poster, inlined so the OG routes can serve real PNG
 * bytes without a filesystem read or any call to the renderer service. The same
 * image is also checked in at public/images/og/intelligence-fallback.png.
 */
export const OG_FALLBACK_PNG_BASE64 =
  "${png.toString("base64")}";

export function ogFallbackPngBytes(): Uint8Array {
  const bin = atob(OG_FALLBACK_PNG_BASE64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
`,
);

console.log(`wrote ${png.length} bytes`);
