/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntelligenceIndexRouteImport } from './routes/intelligence.index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as PartnersApplyRouteImport } from './routes/partners_.apply'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalMethodologyRouteImport } from './routes/legal/methodology'
import { Route as IntelligenceMonthRouteImport } from './routes/intelligence.$month'
import { Route as DemoRightsizeRouteImport } from './routes/demo.rightsize'
import { Route as DemoOverviewRouteImport } from './routes/demo.overview'
import { Route as DemoGovernRouteImport } from './routes/demo.govern'
import { Route as DemoCompareRouteImport } from './routes/demo.compare'
import { Route as DemoCertifyRouteImport } from './routes/demo.certify'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated/workspace.index'
import { Route as AuthenticatedWorkspaceRightsizeRouteImport } from './routes/_authenticated/workspace.rightsize'
import { Route as AuthenticatedWorkspaceGovernRouteImport } from './routes/_authenticated/workspace.govern'
import { Route as AuthenticatedWorkspaceCompareRouteImport } from './routes/_authenticated/workspace.compare'
import { Route as AuthenticatedWorkspaceCertifyRouteImport } from './routes/_authenticated/workspace.certify'
import { Route as AuthenticatedAdminPartnerApplicationsRouteImport } from './routes/_authenticated/admin/partner-applications'
import { Route as ApiPublicWidgetIntelligenceRouteImport } from './routes/api/public/widget/intelligence'
import { Route as ApiPublicV1EventsRouteImport } from './routes/api/public/v1/events'
import { Route as ApiPublicV1BillingRouteImport } from './routes/api/public/v1/billing'
import { Route as ApiPublicSyntheticTickRouteImport } from './routes/api/public/synthetic/tick'
import { Route as ApiPublicSyncPricesRouteImport } from './routes/api/public/sync/prices'
import { Route as ApiPublicSyncFreezeRouteImport } from './routes/api/public/sync/freeze'
import { Route as ApiPublicSyncBenchmarksRouteImport } from './routes/api/public/sync/benchmarks'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicOgIntelligenceMonthRouteImport } from './routes/api/public/og/intelligence/$month'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceIndexRoute = IntelligenceIndexRouteImport.update({
  id: '/intelligence/',
  path: '/intelligence/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const PartnersApplyRoute = PartnersApplyRouteImport.update({
  id: '/partners_/apply',
  path: '/partners/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMethodologyRoute = LegalMethodologyRouteImport.update({
  id: '/legal/methodology',
  path: '/legal/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceMonthRoute = IntelligenceMonthRouteImport.update({
  id: '/intelligence/$month',
  path: '/intelligence/$month',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRightsizeRoute = DemoRightsizeRouteImport.update({
  id: '/rightsize',
  path: '/rightsize',
  getParentRoute: () => DemoRoute,
} as any)
const DemoOverviewRoute = DemoOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DemoRoute,
} as any)
const DemoGovernRoute = DemoGovernRouteImport.update({
  id: '/govern',
  path: '/govern',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCompareRoute = DemoCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCertifyRoute = DemoCertifyRouteImport.update({
  id: '/certify',
  path: '/certify',
  getParentRoute: () => DemoRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceRightsizeRoute =
  AuthenticatedWorkspaceRightsizeRouteImport.update({
    id: '/rightsize',
    path: '/rightsize',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceGovernRoute =
  AuthenticatedWorkspaceGovernRouteImport.update({
    id: '/govern',
    path: '/govern',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceCompareRoute =
  AuthenticatedWorkspaceCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceCertifyRoute =
  AuthenticatedWorkspaceCertifyRouteImport.update({
    id: '/certify',
    path: '/certify',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedAdminPartnerApplicationsRoute =
  AuthenticatedAdminPartnerApplicationsRouteImport.update({
    id: '/admin/partner-applications',
    path: '/admin/partner-applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWidgetIntelligenceRoute =
  ApiPublicWidgetIntelligenceRouteImport.update({
    id: '/api/public/widget/intelligence',
    path: '/api/public/widget/intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1EventsRoute = ApiPublicV1EventsRouteImport.update({
  id: '/api/public/v1/events',
  path: '/api/public/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1BillingRoute = ApiPublicV1BillingRouteImport.update({
  id: '/api/public/v1/billing',
  path: '/api/public/v1/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyntheticTickRoute = ApiPublicSyntheticTickRouteImport.update({
  id: '/api/public/synthetic/tick',
  path: '/api/public/synthetic/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncPricesRoute = ApiPublicSyncPricesRouteImport.update({
  id: '/api/public/sync/prices',
  path: '/api/public/sync/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncFreezeRoute = ApiPublicSyncFreezeRouteImport.update({
  id: '/api/public/sync/freeze',
  path: '/api/public/sync/freeze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncBenchmarksRoute = ApiPublicSyncBenchmarksRouteImport.update({
  id: '/api/public/sync/benchmarks',
  path: '/api/public/sync/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOgIntelligenceMonthRoute =
  ApiPublicOgIntelligenceMonthRouteImport.update({
    id: '/api/public/og/intelligence/$month',
    path: '/api/public/og/intelligence/$month',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/demo': typeof DemoRouteWithChildren
  '/models': typeof ModelsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/demo/certify': typeof DemoCertifyRoute
  '/demo/compare': typeof DemoCompareRoute
  '/demo/govern': typeof DemoGovernRoute
  '/demo/overview': typeof DemoOverviewRoute
  '/demo/rightsize': typeof DemoRightsizeRoute
  '/intelligence/$month': typeof IntelligenceMonthRoute
  '/legal/methodology': typeof LegalMethodologyRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/partners/apply': typeof PartnersApplyRoute
  '/demo/': typeof DemoIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/admin/partner-applications': typeof AuthenticatedAdminPartnerApplicationsRoute
  '/workspace/certify': typeof AuthenticatedWorkspaceCertifyRoute
  '/workspace/compare': typeof AuthenticatedWorkspaceCompareRoute
  '/workspace/govern': typeof AuthenticatedWorkspaceGovernRoute
  '/workspace/rightsize': typeof AuthenticatedWorkspaceRightsizeRoute
  '/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/sync/benchmarks': typeof ApiPublicSyncBenchmarksRoute
  '/api/public/sync/freeze': typeof ApiPublicSyncFreezeRoute
  '/api/public/sync/prices': typeof ApiPublicSyncPricesRoute
  '/api/public/synthetic/tick': typeof ApiPublicSyntheticTickRoute
  '/api/public/v1/billing': typeof ApiPublicV1BillingRoute
  '/api/public/v1/events': typeof ApiPublicV1EventsRoute
  '/api/public/widget/intelligence': typeof ApiPublicWidgetIntelligenceRoute
  '/api/public/og/intelligence/$month': typeof ApiPublicOgIntelligenceMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/models': typeof ModelsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/demo/certify': typeof DemoCertifyRoute
  '/demo/compare': typeof DemoCompareRoute
  '/demo/govern': typeof DemoGovernRoute
  '/demo/overview': typeof DemoOverviewRoute
  '/demo/rightsize': typeof DemoRightsizeRoute
  '/intelligence/$month': typeof IntelligenceMonthRoute
  '/legal/methodology': typeof LegalMethodologyRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/partners/apply': typeof PartnersApplyRoute
  '/demo': typeof DemoIndexRoute
  '/intelligence': typeof IntelligenceIndexRoute
  '/admin/partner-applications': typeof AuthenticatedAdminPartnerApplicationsRoute
  '/workspace/certify': typeof AuthenticatedWorkspaceCertifyRoute
  '/workspace/compare': typeof AuthenticatedWorkspaceCompareRoute
  '/workspace/govern': typeof AuthenticatedWorkspaceGovernRoute
  '/workspace/rightsize': typeof AuthenticatedWorkspaceRightsizeRoute
  '/workspace': typeof AuthenticatedWorkspaceIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/sync/benchmarks': typeof ApiPublicSyncBenchmarksRoute
  '/api/public/sync/freeze': typeof ApiPublicSyncFreezeRoute
  '/api/public/sync/prices': typeof ApiPublicSyncPricesRoute
  '/api/public/synthetic/tick': typeof ApiPublicSyntheticTickRoute
  '/api/public/v1/billing': typeof ApiPublicV1BillingRoute
  '/api/public/v1/events': typeof ApiPublicV1EventsRoute
  '/api/public/widget/intelligence': typeof ApiPublicWidgetIntelligenceRoute
  '/api/public/og/intelligence/$month': typeof ApiPublicOgIntelligenceMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/demo': typeof DemoRouteWithChildren
  '/models': typeof ModelsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/partner': typeof AuthenticatedPartnerRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/demo/certify': typeof DemoCertifyRoute
  '/demo/compare': typeof DemoCompareRoute
  '/demo/govern': typeof DemoGovernRoute
  '/demo/overview': typeof DemoOverviewRoute
  '/demo/rightsize': typeof DemoRightsizeRoute
  '/intelligence/$month': typeof IntelligenceMonthRoute
  '/legal/methodology': typeof LegalMethodologyRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/partners_/apply': typeof PartnersApplyRoute
  '/demo/': typeof DemoIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/_authenticated/admin/partner-applications': typeof AuthenticatedAdminPartnerApplicationsRoute
  '/_authenticated/workspace/certify': typeof AuthenticatedWorkspaceCertifyRoute
  '/_authenticated/workspace/compare': typeof AuthenticatedWorkspaceCompareRoute
  '/_authenticated/workspace/govern': typeof AuthenticatedWorkspaceGovernRoute
  '/_authenticated/workspace/rightsize': typeof AuthenticatedWorkspaceRightsizeRoute
  '/_authenticated/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/sync/benchmarks': typeof ApiPublicSyncBenchmarksRoute
  '/api/public/sync/freeze': typeof ApiPublicSyncFreezeRoute
  '/api/public/sync/prices': typeof ApiPublicSyncPricesRoute
  '/api/public/synthetic/tick': typeof ApiPublicSyntheticTickRoute
  '/api/public/v1/billing': typeof ApiPublicV1BillingRoute
  '/api/public/v1/events': typeof ApiPublicV1EventsRoute
  '/api/public/widget/intelligence': typeof ApiPublicWidgetIntelligenceRoute
  '/api/public/og/intelligence/$month': typeof ApiPublicOgIntelligenceMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/demo'
    | '/models'
    | '/partners'
    | '/pricing'
    | '/sitemap.xml'
    | '/billing'
    | '/partner'
    | '/settings'
    | '/team'
    | '/workspace'
    | '/demo/certify'
    | '/demo/compare'
    | '/demo/govern'
    | '/demo/overview'
    | '/demo/rightsize'
    | '/intelligence/$month'
    | '/legal/methodology'
    | '/legal/privacy'
    | '/legal/terms'
    | '/partners/apply'
    | '/demo/'
    | '/intelligence/'
    | '/admin/partner-applications'
    | '/workspace/certify'
    | '/workspace/compare'
    | '/workspace/govern'
    | '/workspace/rightsize'
    | '/workspace/'
    | '/api/public/payments/webhook'
    | '/api/public/sync/benchmarks'
    | '/api/public/sync/freeze'
    | '/api/public/sync/prices'
    | '/api/public/synthetic/tick'
    | '/api/public/v1/billing'
    | '/api/public/v1/events'
    | '/api/public/widget/intelligence'
    | '/api/public/og/intelligence/$month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/models'
    | '/partners'
    | '/pricing'
    | '/sitemap.xml'
    | '/billing'
    | '/partner'
    | '/settings'
    | '/team'
    | '/demo/certify'
    | '/demo/compare'
    | '/demo/govern'
    | '/demo/overview'
    | '/demo/rightsize'
    | '/intelligence/$month'
    | '/legal/methodology'
    | '/legal/privacy'
    | '/legal/terms'
    | '/partners/apply'
    | '/demo'
    | '/intelligence'
    | '/admin/partner-applications'
    | '/workspace/certify'
    | '/workspace/compare'
    | '/workspace/govern'
    | '/workspace/rightsize'
    | '/workspace'
    | '/api/public/payments/webhook'
    | '/api/public/sync/benchmarks'
    | '/api/public/sync/freeze'
    | '/api/public/sync/prices'
    | '/api/public/synthetic/tick'
    | '/api/public/v1/billing'
    | '/api/public/v1/events'
    | '/api/public/widget/intelligence'
    | '/api/public/og/intelligence/$month'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/demo'
    | '/models'
    | '/partners'
    | '/pricing'
    | '/sitemap.xml'
    | '/_authenticated/billing'
    | '/_authenticated/partner'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/workspace'
    | '/demo/certify'
    | '/demo/compare'
    | '/demo/govern'
    | '/demo/overview'
    | '/demo/rightsize'
    | '/intelligence/$month'
    | '/legal/methodology'
    | '/legal/privacy'
    | '/legal/terms'
    | '/partners_/apply'
    | '/demo/'
    | '/intelligence/'
    | '/_authenticated/admin/partner-applications'
    | '/_authenticated/workspace/certify'
    | '/_authenticated/workspace/compare'
    | '/_authenticated/workspace/govern'
    | '/_authenticated/workspace/rightsize'
    | '/_authenticated/workspace/'
    | '/api/public/payments/webhook'
    | '/api/public/sync/benchmarks'
    | '/api/public/sync/freeze'
    | '/api/public/sync/prices'
    | '/api/public/synthetic/tick'
    | '/api/public/v1/billing'
    | '/api/public/v1/events'
    | '/api/public/widget/intelligence'
    | '/api/public/og/intelligence/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  DemoRoute: typeof DemoRouteWithChildren
  ModelsRoute: typeof ModelsRoute
  PartnersRoute: typeof PartnersRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IntelligenceMonthRoute: typeof IntelligenceMonthRoute
  LegalMethodologyRoute: typeof LegalMethodologyRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PartnersApplyRoute: typeof PartnersApplyRoute
  IntelligenceIndexRoute: typeof IntelligenceIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicSyncBenchmarksRoute: typeof ApiPublicSyncBenchmarksRoute
  ApiPublicSyncFreezeRoute: typeof ApiPublicSyncFreezeRoute
  ApiPublicSyncPricesRoute: typeof ApiPublicSyncPricesRoute
  ApiPublicSyntheticTickRoute: typeof ApiPublicSyntheticTickRoute
  ApiPublicV1BillingRoute: typeof ApiPublicV1BillingRoute
  ApiPublicV1EventsRoute: typeof ApiPublicV1EventsRoute
  ApiPublicWidgetIntelligenceRoute: typeof ApiPublicWidgetIntelligenceRoute
  ApiPublicOgIntelligenceMonthRoute: typeof ApiPublicOgIntelligenceMonthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/': {
      id: '/intelligence/'
      path: '/intelligence'
      fullPath: '/intelligence/'
      preLoaderRoute: typeof IntelligenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/partners_/apply': {
      id: '/partners_/apply'
      path: '/partners/apply'
      fullPath: '/partners/apply'
      preLoaderRoute: typeof PartnersApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/methodology': {
      id: '/legal/methodology'
      path: '/legal/methodology'
      fullPath: '/legal/methodology'
      preLoaderRoute: typeof LegalMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/$month': {
      id: '/intelligence/$month'
      path: '/intelligence/$month'
      fullPath: '/intelligence/$month'
      preLoaderRoute: typeof IntelligenceMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/rightsize': {
      id: '/demo/rightsize'
      path: '/rightsize'
      fullPath: '/demo/rightsize'
      preLoaderRoute: typeof DemoRightsizeRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/overview': {
      id: '/demo/overview'
      path: '/overview'
      fullPath: '/demo/overview'
      preLoaderRoute: typeof DemoOverviewRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/govern': {
      id: '/demo/govern'
      path: '/govern'
      fullPath: '/demo/govern'
      preLoaderRoute: typeof DemoGovernRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/compare': {
      id: '/demo/compare'
      path: '/compare'
      fullPath: '/demo/compare'
      preLoaderRoute: typeof DemoCompareRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/certify': {
      id: '/demo/certify'
      path: '/certify'
      fullPath: '/demo/certify'
      preLoaderRoute: typeof DemoCertifyRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/': {
      id: '/_authenticated/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/rightsize': {
      id: '/_authenticated/workspace/rightsize'
      path: '/rightsize'
      fullPath: '/workspace/rightsize'
      preLoaderRoute: typeof AuthenticatedWorkspaceRightsizeRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/govern': {
      id: '/_authenticated/workspace/govern'
      path: '/govern'
      fullPath: '/workspace/govern'
      preLoaderRoute: typeof AuthenticatedWorkspaceGovernRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/compare': {
      id: '/_authenticated/workspace/compare'
      path: '/compare'
      fullPath: '/workspace/compare'
      preLoaderRoute: typeof AuthenticatedWorkspaceCompareRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/certify': {
      id: '/_authenticated/workspace/certify'
      path: '/certify'
      fullPath: '/workspace/certify'
      preLoaderRoute: typeof AuthenticatedWorkspaceCertifyRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/admin/partner-applications': {
      id: '/_authenticated/admin/partner-applications'
      path: '/admin/partner-applications'
      fullPath: '/admin/partner-applications'
      preLoaderRoute: typeof AuthenticatedAdminPartnerApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/widget/intelligence': {
      id: '/api/public/widget/intelligence'
      path: '/api/public/widget/intelligence'
      fullPath: '/api/public/widget/intelligence'
      preLoaderRoute: typeof ApiPublicWidgetIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/events': {
      id: '/api/public/v1/events'
      path: '/api/public/v1/events'
      fullPath: '/api/public/v1/events'
      preLoaderRoute: typeof ApiPublicV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/billing': {
      id: '/api/public/v1/billing'
      path: '/api/public/v1/billing'
      fullPath: '/api/public/v1/billing'
      preLoaderRoute: typeof ApiPublicV1BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/synthetic/tick': {
      id: '/api/public/synthetic/tick'
      path: '/api/public/synthetic/tick'
      fullPath: '/api/public/synthetic/tick'
      preLoaderRoute: typeof ApiPublicSyntheticTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/prices': {
      id: '/api/public/sync/prices'
      path: '/api/public/sync/prices'
      fullPath: '/api/public/sync/prices'
      preLoaderRoute: typeof ApiPublicSyncPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/freeze': {
      id: '/api/public/sync/freeze'
      path: '/api/public/sync/freeze'
      fullPath: '/api/public/sync/freeze'
      preLoaderRoute: typeof ApiPublicSyncFreezeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/benchmarks': {
      id: '/api/public/sync/benchmarks'
      path: '/api/public/sync/benchmarks'
      fullPath: '/api/public/sync/benchmarks'
      preLoaderRoute: typeof ApiPublicSyncBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/intelligence/$month': {
      id: '/api/public/og/intelligence/$month'
      path: '/api/public/og/intelligence/$month'
      fullPath: '/api/public/og/intelligence/$month'
      preLoaderRoute: typeof ApiPublicOgIntelligenceMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedWorkspaceRouteChildren {
  AuthenticatedWorkspaceCertifyRoute: typeof AuthenticatedWorkspaceCertifyRoute
  AuthenticatedWorkspaceCompareRoute: typeof AuthenticatedWorkspaceCompareRoute
  AuthenticatedWorkspaceGovernRoute: typeof AuthenticatedWorkspaceGovernRoute
  AuthenticatedWorkspaceRightsizeRoute: typeof AuthenticatedWorkspaceRightsizeRoute
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
}

const AuthenticatedWorkspaceRouteChildren: AuthenticatedWorkspaceRouteChildren =
  {
    AuthenticatedWorkspaceCertifyRoute: AuthenticatedWorkspaceCertifyRoute,
    AuthenticatedWorkspaceCompareRoute: AuthenticatedWorkspaceCompareRoute,
    AuthenticatedWorkspaceGovernRoute: AuthenticatedWorkspaceGovernRoute,
    AuthenticatedWorkspaceRightsizeRoute: AuthenticatedWorkspaceRightsizeRoute,
    AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
  }

const AuthenticatedWorkspaceRouteWithChildren =
  AuthenticatedWorkspaceRoute._addFileChildren(
    AuthenticatedWorkspaceRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRouteWithChildren
  AuthenticatedAdminPartnerApplicationsRoute: typeof AuthenticatedAdminPartnerApplicationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRouteWithChildren,
  AuthenticatedAdminPartnerApplicationsRoute:
    AuthenticatedAdminPartnerApplicationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DemoRouteChildren {
  DemoCertifyRoute: typeof DemoCertifyRoute
  DemoCompareRoute: typeof DemoCompareRoute
  DemoGovernRoute: typeof DemoGovernRoute
  DemoOverviewRoute: typeof DemoOverviewRoute
  DemoRightsizeRoute: typeof DemoRightsizeRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoCertifyRoute: DemoCertifyRoute,
  DemoCompareRoute: DemoCompareRoute,
  DemoGovernRoute: DemoGovernRoute,
  DemoOverviewRoute: DemoOverviewRoute,
  DemoRightsizeRoute: DemoRightsizeRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  DemoRoute: DemoRouteWithChildren,
  ModelsRoute: ModelsRoute,
  PartnersRoute: PartnersRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IntelligenceMonthRoute: IntelligenceMonthRoute,
  LegalMethodologyRoute: LegalMethodologyRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PartnersApplyRoute: PartnersApplyRoute,
  IntelligenceIndexRoute: IntelligenceIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicSyncBenchmarksRoute: ApiPublicSyncBenchmarksRoute,
  ApiPublicSyncFreezeRoute: ApiPublicSyncFreezeRoute,
  ApiPublicSyncPricesRoute: ApiPublicSyncPricesRoute,
  ApiPublicSyntheticTickRoute: ApiPublicSyntheticTickRoute,
  ApiPublicV1BillingRoute: ApiPublicV1BillingRoute,
  ApiPublicV1EventsRoute: ApiPublicV1EventsRoute,
  ApiPublicWidgetIntelligenceRoute: ApiPublicWidgetIntelligenceRoute,
  ApiPublicOgIntelligenceMonthRoute: ApiPublicOgIntelligenceMonthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
