/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicSyntheticTickRouteImport } from './routes/api/public/synthetic/tick'
import { Route as ApiPublicSyncBenchmarksRouteImport } from './routes/api/public/sync/benchmarks'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyntheticTickRoute = ApiPublicSyntheticTickRouteImport.update({
  id: '/api/public/synthetic/tick',
  path: '/api/public/synthetic/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncBenchmarksRoute = ApiPublicSyncBenchmarksRouteImport.update({
  id: '/api/public/sync/benchmarks',
  path: '/api/public/sync/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/sync/benchmarks': typeof ApiPublicSyncBenchmarksRoute
  '/api/public/synthetic/tick': typeof ApiPublicSyntheticTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/sync/benchmarks': typeof ApiPublicSyncBenchmarksRoute
  '/api/public/synthetic/tick': typeof ApiPublicSyntheticTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/sync/benchmarks': typeof ApiPublicSyncBenchmarksRoute
  '/api/public/synthetic/tick': typeof ApiPublicSyntheticTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/public/ingest'
    | '/api/public/sync/benchmarks'
    | '/api/public/synthetic/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/public/ingest'
    | '/api/public/sync/benchmarks'
    | '/api/public/synthetic/tick'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/public/ingest'
    | '/api/public/sync/benchmarks'
    | '/api/public/synthetic/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicSyncBenchmarksRoute: typeof ApiPublicSyncBenchmarksRoute
  ApiPublicSyntheticTickRoute: typeof ApiPublicSyntheticTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/synthetic/tick': {
      id: '/api/public/synthetic/tick'
      path: '/api/public/synthetic/tick'
      fullPath: '/api/public/synthetic/tick'
      preLoaderRoute: typeof ApiPublicSyntheticTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/benchmarks': {
      id: '/api/public/sync/benchmarks'
      path: '/api/public/sync/benchmarks'
      fullPath: '/api/public/sync/benchmarks'
      preLoaderRoute: typeof ApiPublicSyncBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicSyncBenchmarksRoute: ApiPublicSyncBenchmarksRoute,
  ApiPublicSyntheticTickRoute: ApiPublicSyntheticTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
